spring:
  application:
    name: java-telegram-notifier

app:
  config-file-path: /app/config/config.yaml

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    com.icaroerasmo: DEBUG
