telegram-notifier:
  locale: 'pt-BR'
  min-send-interval-ms: 2000
  telegram:
    chat-id: '${TELEGRAM_CHAT_ID}'
    bot-token: '${TELEGRAM_BOT_TOKEN}'
spring:
  rabbitmq:
    host: '${RABBITMQ_HOST:localhost}'
    port: ${RABBITMQ_PORT:5672}
    username: '${RABBITMQ_USERNAME:guest}'
    password: '${RABBITMQ_PASSWORD:guest}'
    publisher-confirm-type: correlated
    publisher-returns: true
